### PR TITLE
feature: spatial reference systems

### PR DESCRIPTION
**Pull request by niniemann**
This PR builds upon #3 and adds spatial reference systems to the game. Geographic coordinate systems (latitude, longitude), projections (UTM, equirectangular) and additionally chained local affine transformations are supported.

### CODE REVIEW

**Comment by niniemann** [comment]
@Kynneb I know you wanted this to look a bit... different. ^^ We can still overload e.g. the transformToCS method to directly use another entity::Geometry here. Over time we will add more functionality, right now we can e.g. only change the existing entity, but not return a modified variant. (Or maybe just provide a clone() method?)

**Comment by Kynneb** [comment]
Strangely enough (as the automated tests pass) I get a compilation error:
```SEMPR/src/../include/sempr/entity/spatial/CurvePolygon.hpp:21:5: error: ‘OGRCurvePolygon’ does not name a type
```

**Comment by niniemann** [comment]
Sorry if this is too fast, but I'll merge this now. It's not like discarding this PR would be an option, anyway. Feel free to create issues if something's wrong. But I need it merged. :)

**Comment by Kynneb** [comment]
Woah, okay. I see you are hurrying up. Still trying to figure out the linking error anyway, so have fun. I will create an issue for that when I have more info.

**Pull request merged**
