### PR TITLE
WIP: Bulk database updates

### PR DESCRIPTION
**Pull request by Kynneb**
As discussed in #6

### CODE REVIEW

**Comment by niniemann** [comment]
I think I've found a ~more or~ less serious problem with bulk updates. Consider the following:

things to do | entities-to-save-list | comment
---------------|-----------------------|-------------
create A      | A |
create B      | A, B |
let A point to B (A->changed()) | A, B | A is already in the list, nothing to change **?!**
"synchronize" | | A will be persisted first, which creates a foreign key constraint violation as B does not exist in the database yet.

I can think of three solutions:

1. Disable foreign key constrains for the update transaction.
2. Always persist entities as soon as they are created, but "collect" changes and update them only when told to.
3. Split changes into three categories, and process them in this order.
    1. Newly created
    2. Changed
    3. Removed

The idea for number **3.** just came to me while writing this issue (thanks for rubber-ducking? ;-)). I'll go for this solution, but feel free to correct me if this will break anything. One minor question, just out of interest: If we split it like this, is it even necessary to keep the order of "changed"-events in step 2? I mean, theoretically, we would let
```
A->changed();
B->changed();
A->changed();
updater->sync();
```
lead to 
```
save(A);
save(B);
```
though the first change of A could be totally reversed by the second one, which could instead depend on the change of B. Theoretically. Practically I can't find a concrete example to break stuff with this, and we really can't account for every eventuality...

**Comment by niniemann** [comment]
Wait!
 
/ | to persist | to update | comment
---|---|---|---
A->created() | A |
B->created() | A, B |
A->pointTo(B) | A, B | A
updater->sync() | | | breaks "solution" **3**. As when A is persisted, B does not exist in the database yet.

Solution 3 doesn't even work for my first example. Damn. So, I'll go for **2** then. Immediately persist newly created entities. If we really run into performance-issues due to creating too many entities at once we can still think of a mass-creation-routine. Like, explicitly collecting created entities, and warning the user what can go wrong with that in the documentation.

**Comment by niniemann** [comment]
I guess this should work now... what do you think, @Kynneb ?

**Comment by niniemann** [comment]
**TODO:** Remove Storage::Ptr from Core-ctor. It should not be needed anymore.

**Comment by Kynneb** [comment]
Looks good on first (and second glance) I wonder if some more unit tests would be nice to explicitly test the scenarios mentioned above.

**Pull request merged**
