### PR TITLE
README: Use shallow clone of gdal

### PR DESCRIPTION
**Pull request by mintar**
This reduces the download size from 1.6 GB to 144 MB

### CODE REVIEW

**Comment by niniemann** [comment]
I think you may have compared your compiled version of gdal with the pure source code.
My gdal installation (source + compiled + installed) reports:
```
$ du -hs gdal/
1,8G    gdal/
```
While the pure source is much smaller:
```
$ du -hs gdal_deep/
316M    gdal_deep/

$ du -hs gdal_shallow/
144M    gdal_shallow/
```
Nevertheless, I won't say no to free disk space, though the overall improvement is not huge. :wink:

**Comment by mintar** [comment]
Feel free to click "merge" then. :)

**Comment by niniemann** [comment]
I thought I'd wait for the branch [remove_gdal](/sempr-tk/sempr/tree/remove_gdal) to be finished which will close #19 and thus make this change obsolete. :) This is currently in progress.

**Comment by mintar** [comment]
Ah, ok, no problem. Feel free to close this PR.

**Pull request closed without merging**
